version: '3'

services:
  dev:
    image: node:12.10.0
    depends_on:
      - postgres
      - redis
    volumes:
      - nodemodules:/usr/src/service/node_modules
      - .:/usr/src/service
    working_dir: /usr/src/service
    environment:
      - NODE_ENV=development
      - REDIS_HOST=redis
      - DOCKER_POSTGRES=true
    command: npm run dev
    ports:
      - 9500:9500
      - 9229:9229 # For debugger

  postgres:
    image: postgres:11.2-alpine
    environment:
      - POSTGRES_USER=hackathon
      - POSTGRES_PASSWORD=
      - POSTGRES_DB=runregistry_database
    ports:
      - '6543:5432'

  redis:
    image: redis:5.0.7-alpine
    hostname: redis
    volumes:
      - redis_data:/data
    ports:
      - 6379:6379

volumes:
  nodemodules:
    external: true
  redis_data:
